#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZKTEchoTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GaposaHR")]
	public partial class lnqAttendanceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStaffDetail(StaffDetail instance);
    partial void UpdateStaffDetail(StaffDetail instance);
    partial void DeleteStaffDetail(StaffDetail instance);
    partial void InsertStaffAttendance(StaffAttendance instance);
    partial void UpdateStaffAttendance(StaffAttendance instance);
    partial void DeleteStaffAttendance(StaffAttendance instance);
    #endregion
		
		public lnqAttendanceDataContext() : 
				base(global::ZKTEchoTest.Properties.Settings.Default.GaposaHRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public lnqAttendanceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lnqAttendanceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lnqAttendanceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lnqAttendanceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StaffDetail> StaffDetails
		{
			get
			{
				return this.GetTable<StaffDetail>();
			}
		}
		
		public System.Data.Linq.Table<StaffAttendance> StaffAttendances
		{
			get
			{
				return this.GetTable<StaffAttendance>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StaffDetails")]
	public partial class StaffDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StaffID;
		
		private string _FileNo;
		
		private string _Surname;
		
		private string _Firstname;
		
		private string _Othername;
		
		private System.Nullable<int> _GenderID;
		
		private System.Nullable<int> _MaritalStatusID;
		
		private string _Email;
		
		private string _Phone;
		
		private string _Address;
		
		private int _DesignationID;
		
		private System.Nullable<int> _LevelID;
		
		private System.Nullable<int> _StepID;
		
		private System.Nullable<int> _QualificationID;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private System.Nullable<System.DateTime> _DateOfFirstAppointment;
		
		private System.Nullable<System.DateTime> _DateOfPresentAppointment;
		
		private System.Nullable<System.DateTime> _ExpectedRetirementDate;
		
		private System.Nullable<System.DateTime> _CurrentPromotionDate;
		
		private System.Nullable<System.DateTime> _ProposedPromotionDate;
		
		private System.Nullable<int> _DepartmentID;
		
		private System.Nullable<int> _StateID;
		
		private System.Nullable<int> _LGAID;
		
		private string _Password;
		
		private int _AppRoleID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaffIDChanging(int value);
    partial void OnStaffIDChanged();
    partial void OnFileNoChanging(string value);
    partial void OnFileNoChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnOthernameChanging(string value);
    partial void OnOthernameChanged();
    partial void OnGenderIDChanging(System.Nullable<int> value);
    partial void OnGenderIDChanged();
    partial void OnMaritalStatusIDChanging(System.Nullable<int> value);
    partial void OnMaritalStatusIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnDesignationIDChanging(int value);
    partial void OnDesignationIDChanged();
    partial void OnLevelIDChanging(System.Nullable<int> value);
    partial void OnLevelIDChanged();
    partial void OnStepIDChanging(System.Nullable<int> value);
    partial void OnStepIDChanged();
    partial void OnQualificationIDChanging(System.Nullable<int> value);
    partial void OnQualificationIDChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnDateOfFirstAppointmentChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfFirstAppointmentChanged();
    partial void OnDateOfPresentAppointmentChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfPresentAppointmentChanged();
    partial void OnExpectedRetirementDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpectedRetirementDateChanged();
    partial void OnCurrentPromotionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCurrentPromotionDateChanged();
    partial void OnProposedPromotionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProposedPromotionDateChanged();
    partial void OnDepartmentIDChanging(System.Nullable<int> value);
    partial void OnDepartmentIDChanged();
    partial void OnStateIDChanging(System.Nullable<int> value);
    partial void OnStateIDChanged();
    partial void OnLGAIDChanging(System.Nullable<int> value);
    partial void OnLGAIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAppRoleIDChanging(int value);
    partial void OnAppRoleIDChanged();
    #endregion
		
		public StaffDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this.OnStaffIDChanging(value);
					this.SendPropertyChanging();
					this._StaffID = value;
					this.SendPropertyChanged("StaffID");
					this.OnStaffIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FileNo
		{
			get
			{
				return this._FileNo;
			}
			set
			{
				if ((this._FileNo != value))
				{
					this.OnFileNoChanging(value);
					this.SendPropertyChanging();
					this._FileNo = value;
					this.SendPropertyChanged("FileNo");
					this.OnFileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this.OnFirstnameChanging(value);
					this.SendPropertyChanging();
					this._Firstname = value;
					this.SendPropertyChanged("Firstname");
					this.OnFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Othername", DbType="VarChar(50)")]
		public string Othername
		{
			get
			{
				return this._Othername;
			}
			set
			{
				if ((this._Othername != value))
				{
					this.OnOthernameChanging(value);
					this.SendPropertyChanging();
					this._Othername = value;
					this.SendPropertyChanged("Othername");
					this.OnOthernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderID", DbType="Int")]
		public System.Nullable<int> GenderID
		{
			get
			{
				return this._GenderID;
			}
			set
			{
				if ((this._GenderID != value))
				{
					this.OnGenderIDChanging(value);
					this.SendPropertyChanging();
					this._GenderID = value;
					this.SendPropertyChanged("GenderID");
					this.OnGenderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatusID", DbType="Int")]
		public System.Nullable<int> MaritalStatusID
		{
			get
			{
				return this._MaritalStatusID;
			}
			set
			{
				if ((this._MaritalStatusID != value))
				{
					this.OnMaritalStatusIDChanging(value);
					this.SendPropertyChanging();
					this._MaritalStatusID = value;
					this.SendPropertyChanged("MaritalStatusID");
					this.OnMaritalStatusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(200)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesignationID", DbType="Int NOT NULL")]
		public int DesignationID
		{
			get
			{
				return this._DesignationID;
			}
			set
			{
				if ((this._DesignationID != value))
				{
					this.OnDesignationIDChanging(value);
					this.SendPropertyChanging();
					this._DesignationID = value;
					this.SendPropertyChanged("DesignationID");
					this.OnDesignationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelID", DbType="Int")]
		public System.Nullable<int> LevelID
		{
			get
			{
				return this._LevelID;
			}
			set
			{
				if ((this._LevelID != value))
				{
					this.OnLevelIDChanging(value);
					this.SendPropertyChanging();
					this._LevelID = value;
					this.SendPropertyChanged("LevelID");
					this.OnLevelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StepID", DbType="Int")]
		public System.Nullable<int> StepID
		{
			get
			{
				return this._StepID;
			}
			set
			{
				if ((this._StepID != value))
				{
					this.OnStepIDChanging(value);
					this.SendPropertyChanging();
					this._StepID = value;
					this.SendPropertyChanged("StepID");
					this.OnStepIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QualificationID", DbType="Int")]
		public System.Nullable<int> QualificationID
		{
			get
			{
				return this._QualificationID;
			}
			set
			{
				if ((this._QualificationID != value))
				{
					this.OnQualificationIDChanging(value);
					this.SendPropertyChanging();
					this._QualificationID = value;
					this.SendPropertyChanged("QualificationID");
					this.OnQualificationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfFirstAppointment", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfFirstAppointment
		{
			get
			{
				return this._DateOfFirstAppointment;
			}
			set
			{
				if ((this._DateOfFirstAppointment != value))
				{
					this.OnDateOfFirstAppointmentChanging(value);
					this.SendPropertyChanging();
					this._DateOfFirstAppointment = value;
					this.SendPropertyChanged("DateOfFirstAppointment");
					this.OnDateOfFirstAppointmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfPresentAppointment", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfPresentAppointment
		{
			get
			{
				return this._DateOfPresentAppointment;
			}
			set
			{
				if ((this._DateOfPresentAppointment != value))
				{
					this.OnDateOfPresentAppointmentChanging(value);
					this.SendPropertyChanging();
					this._DateOfPresentAppointment = value;
					this.SendPropertyChanged("DateOfPresentAppointment");
					this.OnDateOfPresentAppointmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedRetirementDate", DbType="Date")]
		public System.Nullable<System.DateTime> ExpectedRetirementDate
		{
			get
			{
				return this._ExpectedRetirementDate;
			}
			set
			{
				if ((this._ExpectedRetirementDate != value))
				{
					this.OnExpectedRetirementDateChanging(value);
					this.SendPropertyChanging();
					this._ExpectedRetirementDate = value;
					this.SendPropertyChanged("ExpectedRetirementDate");
					this.OnExpectedRetirementDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentPromotionDate", DbType="Date")]
		public System.Nullable<System.DateTime> CurrentPromotionDate
		{
			get
			{
				return this._CurrentPromotionDate;
			}
			set
			{
				if ((this._CurrentPromotionDate != value))
				{
					this.OnCurrentPromotionDateChanging(value);
					this.SendPropertyChanging();
					this._CurrentPromotionDate = value;
					this.SendPropertyChanged("CurrentPromotionDate");
					this.OnCurrentPromotionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProposedPromotionDate", DbType="Date")]
		public System.Nullable<System.DateTime> ProposedPromotionDate
		{
			get
			{
				return this._ProposedPromotionDate;
			}
			set
			{
				if ((this._ProposedPromotionDate != value))
				{
					this.OnProposedPromotionDateChanging(value);
					this.SendPropertyChanging();
					this._ProposedPromotionDate = value;
					this.SendPropertyChanged("ProposedPromotionDate");
					this.OnProposedPromotionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int")]
		public System.Nullable<int> DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this.OnDepartmentIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmentID = value;
					this.SendPropertyChanged("DepartmentID");
					this.OnDepartmentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateID", DbType="Int")]
		public System.Nullable<int> StateID
		{
			get
			{
				return this._StateID;
			}
			set
			{
				if ((this._StateID != value))
				{
					this.OnStateIDChanging(value);
					this.SendPropertyChanging();
					this._StateID = value;
					this.SendPropertyChanged("StateID");
					this.OnStateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LGAID", DbType="Int")]
		public System.Nullable<int> LGAID
		{
			get
			{
				return this._LGAID;
			}
			set
			{
				if ((this._LGAID != value))
				{
					this.OnLGAIDChanging(value);
					this.SendPropertyChanging();
					this._LGAID = value;
					this.SendPropertyChanged("LGAID");
					this.OnLGAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppRoleID", DbType="Int NOT NULL")]
		public int AppRoleID
		{
			get
			{
				return this._AppRoleID;
			}
			set
			{
				if ((this._AppRoleID != value))
				{
					this.OnAppRoleIDChanging(value);
					this.SendPropertyChanging();
					this._AppRoleID = value;
					this.SendPropertyChanged("AppRoleID");
					this.OnAppRoleIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StaffAttendance")]
	public partial class StaffAttendance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SAID;
		
		private string _FileNo;
		
		private System.Nullable<System.DateTime> _AttendanceDate;
		
		private System.Nullable<System.TimeSpan> _SignIn;
		
		private System.Nullable<System.TimeSpan> _SignOut;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSAIDChanging(int value);
    partial void OnSAIDChanged();
    partial void OnFileNoChanging(string value);
    partial void OnFileNoChanged();
    partial void OnAttendanceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAttendanceDateChanged();
    partial void OnSignInChanging(System.Nullable<System.TimeSpan> value);
    partial void OnSignInChanged();
    partial void OnSignOutChanging(System.Nullable<System.TimeSpan> value);
    partial void OnSignOutChanged();
    #endregion
		
		public StaffAttendance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SAID
		{
			get
			{
				return this._SAID;
			}
			set
			{
				if ((this._SAID != value))
				{
					this.OnSAIDChanging(value);
					this.SendPropertyChanging();
					this._SAID = value;
					this.SendPropertyChanged("SAID");
					this.OnSAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FileNo
		{
			get
			{
				return this._FileNo;
			}
			set
			{
				if ((this._FileNo != value))
				{
					this.OnFileNoChanging(value);
					this.SendPropertyChanging();
					this._FileNo = value;
					this.SendPropertyChanged("FileNo");
					this.OnFileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendanceDate", DbType="Date")]
		public System.Nullable<System.DateTime> AttendanceDate
		{
			get
			{
				return this._AttendanceDate;
			}
			set
			{
				if ((this._AttendanceDate != value))
				{
					this.OnAttendanceDateChanging(value);
					this.SendPropertyChanging();
					this._AttendanceDate = value;
					this.SendPropertyChanged("AttendanceDate");
					this.OnAttendanceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignIn", DbType="Time")]
		public System.Nullable<System.TimeSpan> SignIn
		{
			get
			{
				return this._SignIn;
			}
			set
			{
				if ((this._SignIn != value))
				{
					this.OnSignInChanging(value);
					this.SendPropertyChanging();
					this._SignIn = value;
					this.SendPropertyChanged("SignIn");
					this.OnSignInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignOut", DbType="Time")]
		public System.Nullable<System.TimeSpan> SignOut
		{
			get
			{
				return this._SignOut;
			}
			set
			{
				if ((this._SignOut != value))
				{
					this.OnSignOutChanging(value);
					this.SendPropertyChanging();
					this._SignOut = value;
					this.SendPropertyChanged("SignOut");
					this.OnSignOutChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
